### ISSUE TITLE
Fails to build with aml 0.2.2

### ISSUE THREAD

**Issue by emersion** [any1/wlvncc#20]
```
ninja: Entering directory `build/'
[19/33] Compiling C object wlvncc.p/src_main.c.o
FAILED: wlvncc.p/src_main.c.o 
cc -Iwlvncc.p -I. -I.. -I../include -I../src/encodings -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/p11-kit-1 -I/usr/include/libpng16 -I/usr/include/lzo -fdiagnostics-color=always -fsanitize=address,undefined -fno-omit-frame-pointer -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu11 -O0 -g -D_GNU_SOURCE -DAML_UNSTABLE_API=1 -MD -MQ wlvncc.p/src_main.c.o -MF wlvncc.p/src_main.c.o.d -o wlvncc.p/src_main.c.o -c ../src/main.c
../src/main.c: In function ‘main’:
../src/main.c:908:13: error: ‘aml_unstable_abi_version’ undeclared (first use in this function)
  908 |         if (aml_unstable_abi_version != AML_UNSTABLE_API) {
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
../src/main.c:908:13: note: each undeclared identifier is reported only once for each function it appears in
[32/33] Compiling C object wlvncc.p/src_rfbproto.c.o
ninja: build stopped: subcommand failed.
```

**Comment by emersion** [comment]
Hm, is wlvncc git supposed to always be built with aml git?

**Comment by any1** [comment]
> Hm, is wlvncc git supposed to always be built with aml git?

Yes, preferably, since neither are stable currently.

However, I do not foresee changing the aml interface from now on, and I'm planning to release stable aml and neatvnc soon. wlvncc 1.0 is not happening any time soon though.

**Comment by emersion** [comment]
Okay, makes sense, let's close this now. Would be nice to update the version constraint in `meson.build` when that happens.
